apiVersion: apps/v1
kind: Deployment
metadata:
  name: teta-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teta-app
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: teta-app
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.6.2
          resources:
            requests:
              memory: "100Mi"
              cpu: 100m
            limits:
              memory: "100Mi"
              cpu: 100m
          ports:
            - containerPort: 9898
              name: http
          env:
            - name: teta-1
              valueFrom:
                configMapKeyRef:
                  name: teta-config
                  key: APP_MODE
            - name: teta-2
              valueFrom:
                configMapKeyRef:
                  name: teta-config
                  key: APP_PORT
